### ISSUE TITLE
Let's use type hints!

### ISSUE THREAD

**Issue by tailaiw** [arundo/adtk#1]
We like to start using type hints for better practice of python programming. For a first-time contributor, this is probably a nice starting point, as you will go through every part of the code base and familiarize yourself with the code structure. 

To-do's:

- [ ] Add type hints to all functions.
- [ ] Modify docstrings accordingly, so sphinx-autodoc will automatically grab type info from type hints.
- [ ] Add unit tests (with mypy?) for type checking.

Have fun!

**Comment by jason-hu7** [comment]
I will work on this issue.

**Comment by anders-albert** [comment]
I am starting to look into this package. As far as I see you use the numpy documentation standard. Are you strict on this or is google style documentation working just as well? I understand that the sphinx extension sphinx.ext.napoleon works with both.

**Comment by tailaiw** [comment]
@anders-albert yes we require numpy style in ADTK, but technically Google style works too. We just picked one that looks slightly better in our case.

**Comment by Rendiere** [comment]
Does this issue still need help?

**Comment by tailaiw** [comment]
I'm not sure if anyone is working on it. @jason-hu7 are you?

**Comment by tellezsanti** [comment]
I'll work on this, on the type-hints-santi branch

**Comment by tailaiw** [comment]
Done by #79 #86
