### ISSUE TITLE
What is c? 

### ISSUE THREAD

**Issue by Anaisdg** [arundo/adtk#108]
Can you please explain what exactly is `c (float, optional) – Factor used to determine the bound of normal range based on historical interquartile range. Default: 3.0.` ?
And is it the same for all functions that use it? 
Thank you.

**Comment by tailaiw** [comment]
For detectors that are internally implemented as pipeline or pipenet, `c` is the parameter of the `InterquartileRangeAD` detector in the pipe. For details about how the parameter control `InterqaurtileRangeAD`, you may refer to its documentation.

**Comment by Anaisdg** [comment]
Thank you!
