### ISSUE TITLE
Adding a third example to DoubleRollingAggregate that shows Spikes

### ISSUE THREAD

**Issue by yy910616** [arundo/adtk#41]
Hello,
The difference between PersistAD / LevelShiftAD, while explained in the documentation, could use a bit more clarification. This is just a personal opinion, please check if others feel the same if possible. 
If I'm reading the doc and code correctly, both PersistAD / LevelShiftAD are implemented with DoubleRollingAggregate as transformers, but PersistAD has one window fixed to length of 1, while the other window can be controlled by a window variable. Whereas for LevelShiftAD, both window in the DoubleRollingAggregate are allow to vary via the window variable. Also somewhat importantly, LevelShiftAD only looks at median, which allows it to ignore spikes. Does this sound right?

I propose one of the following changes:
1.  Leave a note in either the [PersisAD](https://arundo-adtk.readthedocs-hosted.com/en/stable/notebooks/demo.html#PersistAD) section or the [LevelShiftAD](https://arundo-adtk.readthedocs-hosted.com/en/stable/notebooks/demo.html#LevelShiftAD) section that explicitly states the difference between the two implementations.
2. This is my vote: we could add another example to the [DoubleRollingAggregate](https://arundo-adtk.readthedocs-hosted.com/en/stable/notebooks/demo.html#DoubleRollingAggregate) section. You already have an example setup under PersisAD, we could just modify the code a bit and add it in. IMO, this would highlight the window variable in DoubleRollingAggregate, and indirectly lead to a better understanding of PersistAD / LevelShiftAD.

Please let me know your thoughts! I'm happy to open a PR if need be.
Thank you

**Comment by tailaiw** [comment]
@yy910616 Thanks for the great suggestion. Please go ahead to open a PR.

**Comment by tailaiw** [comment]
Done by #43
