### ISSUE TITLE
Deprecation from statsmodels

### ISSUE THREAD

**Issue by tellezsanti** [arundo/adtk#61]
You are using statsmodels 0.11, 'freq' is deprecated in the ClassicSeasonalDecomposition() function

![Screen Shot 2020-02-05 at 2 57 51 PM](https://user-images.githubusercontent.com/29239487/73882583-eddf9a00-4827-11ea-87dc-cbb0b1a7bade.png)

**Comment by tailaiw** [comment]
Thanks for catching this. Apparently this is something new introduced by the 0.11 release of statsmodels. We will take care of it in the next release.

**Comment by tailaiw** [comment]
Fixed by #72
