### ISSUE TITLE
Does it returns an anomaly score ?

### ISSUE THREAD

**Issue by engineeryashsaxena** [arundo/adtk#75]
Do the detectors of ADTK returns anomaly score ? If yes, then using which parameters I can get them ?

**Comment by engineeryashsaxena** [comment]
@tailaiw Pls let me know

**Comment by tailaiw** [comment]
@engineeryashsaxena ADTK models have a `score` method for the model evaluation purpose, like the scikit-learn score method of estimators. But I assume you're asking about "score" that indicates the severity/probability of detected anomalies, right? If so, we do not have this functionality.

**Comment by engineeryashsaxena** [comment]
Thanks @tailaiw for the clarification
