### ISSUE TITLE
Quickstart lacks info on required data files

### ISSUE THREAD

**Issue by robmarkcole** [arundo/adtk#9]
Hi
in the [quickstart guide](https://arundo-adtk.readthedocs-hosted.com/en/latest/quickstart.html) you point ot the nyc taxi dataset on the [Numenta Anomaly Benchmark](https://github.com/numenta/NAB) but do not provide the links to the files required (or transformations to generat them). I have located `training.csv` as `NAB/data/realKnownCause/nyc_taxi.csv` but have not located `known_anomalies.csv`
Thanks

**Comment by tailaiw** [comment]
We hand-labeled the time series by eyeballing the data, just for a quick demo purpose.

**Comment by CharlyWargnier** [comment]
I couldn't find that file, thanks Rob for pointing that out! :)

**Comment by tysend** [comment]
It's also unclear what NAB file was used for testing.csv.
